spring:
  redis:
    redisson:
      enable: true
      singleServerConfig:
        idleConnectionTimeout: 10000
        connectTimeout: 10000
        timeout: 3000
        retryAttempts: 3
        retryInterval: 1500
        subscriptionsPerConnection: 5
        address: redis://localhost:6379
        subscriptionConnectionMinimumIdleSize: 1
        subscriptionConnectionPoolSize: 50
        connectionMinimumIdleSize: 10
        connectionPoolSize: 64
        dnsMonitoringInterval: 5000
        codec:
          class: org.redisson.client.codec.StringCodec
            

city:
  service:
    url: http://localhost:1010